spring:
  datasource:
    url: jdbc:mysql://testdb:3306/deploy_server?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&&zeroDateTimeBehavior=convertToNull
    username: test
    password: test
  jpa:
    hibernate.ddl-auto: "update"
  task:
    scheduling:
      thread-name-prefix: "scheduling-"
      pool.size: 1

logging:
  file:
    path: logs
  level:
    root: WARN
    net.arksea.ansible.deploy: INFO


job:
  workRoot: /home/ansible-deploy/job-work
  logExpireDays: 30
  notify:
    mail:
      username: test-devop@qq.com
      password: 1234
      from: test-devop@qq.com

