spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/test
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create

mariaDB4j:
  port: 3307
  dataDir: target/mariadb4j/data
  baseDir: target/mariadb4j/base
  charSet: utf8
  collection: utf8_general_ci

logging:
  level:
    root: WARN
    net.arksea.ansible.deploy: DEBUG

job:
  workRoot: ./job-work
  logExpireDays: 1
  notify:
    mail:
      username: test-devop@qq.com
      password: 1234
      from: test-devop@qq.com
